spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.145.184:8848
    sentinel:
      transport:
        dashboard: 39.105.145.184:8888

server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: "*"