spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.145.184:8848
server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: "*"